apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhtap-go-app-27
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-go-app-27 
  name: rhtap-go-app-27
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhtap-go-app-27 
